### ISSUE TITLE
ERROR:root:Unable to process traindata.json

### ISSUE THREAD

**Issue by RAJANAGORI** [DataTurks-Engg/Entity-Recognition-In-Resumes-SpaCy#12]
error = 'NoneType' object is not iterable
Traceback (most recent call last):
  File "<ipython-input-26-1169b0efbb3b>", line 22, in convert_dataturks_to_spacy
    for annotation in data['annotation']:
TypeError: 'NoneType' object is not iterable
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-6b61c2d740cf> in <module>
----> 1 train_spacy()

<ipython-input-26-1169b0efbb3b> in train_spacy()
     51 
     52     # add labels
---> 53     for _, annotations in TRAIN_DATA:
     54          for ent in annotations.get('entities'):
     55             ner.add_label(ent[2])

TypeError: 'NoneType' object is not iterable

_**getting this error after function calling**_

**Comment by skanda44** [comment]
what is the solution for this?

**Comment by karthikgauti** [comment]
anyone has solution for this?

**Comment by akj2784** [comment]
Same error at my end

**Comment by rahulsarkar906** [comment]
same error at my end.

**Comment by SafiaKhaleel** [comment]
@RAJANAGORI  Did you solve the issue? I'm also getting the same error

**Comment by Marisamy01** [comment]
Replace "with open(dataturks_JSON_FilePath, 'r') as f:"  this line with open(dataturks_JSON_FilePath, 'r',encoding='utf-8') as f:

It works for me
