### ISSUE TITLE
can someone please resolve this

### ISSUE THREAD

**Issue by pingaliSravanthi** [DataTurks-Engg/Entity-Recognition-In-Resumes-SpaCy#20]
![image](https://user-images.githubusercontent.com/49191347/68271426-74000f00-0086-11ea-975c-88bcf6d8cedc.jpg)

**Comment by Abhimanyu100** [comment]
You need to write `encoding="utf8"` in this line. Something like this `with open(dataturks_JSON_FilePath, 'r', encoding="utf-8") as f:
            lines = f.readlines()`
