### ISSUE TITLE
Annotated Resume Link isn't working Properly

### ISSUE THREAD

**Issue by wasi0013** [DataTurks-Engg/Entity-Recognition-In-Resumes-SpaCy#4]
The link to download 220 annotated resumes in the README.md isn't working.

https://dataturks.com/projects/abhishek.narayanan/Entity

Can you provide the dataset?

**Comment by set92** [comment]
That's because you have to change the spaces to %20, and you will end up with https://dataturks.com/projects/abhishek.narayanan/Entity%20Recognition%20in%20Resumes

I did a pull request to fix it for the future.

**Comment by The-Gupta** [comment]
@wasi0013 , [Here](https://www.kaggle.com/dataturks/resume-entities-for-ner)'s the dataset.

**Comment by wasi0013** [comment]
thanks
